### ISSUE TITLE
AD2 Ready Open

### ISSUE THREAD

**Issue by j3tang** [nutechsoftware/alarmdecoder#32]
Just recently got AlarmDecoder setup with SmartThings via AD2Pi device with my own provided RPi.

However, when I arm the system through SmartThings SHM the AD2 Ready contact opens and immediately indicates that there is an intrusion detected, I get a text message indicating the intrusion, and SHM also indicates that the "siren and audio were muted"

When the system is not armed, AD2 Ready will flip between open/close as motion sensors etc are tripped. 

Any ideas what the issue might be?

**Comment by f34rdotcom** [comment]
Sounds like multiple issues. What I suspect from symptoms.
1. Multiple partitions. Please include info on panel type and partition info and a short panel message dump from ser2sock port 10000.
2. tty device on linux is being used by multiple processes. For example serial console as well as AlarmDecoder device.
3. Possibly not configured hardware overlay and the hardware uart is not routed to the AlarmDecoder correctly.

**Comment by j3tang** [comment]
Thanks for quick response!

This is setup on a Vista 20p, however, with just 1 partition. There are 3 wired motion detectors, 4 wired door contacts, 3 wireless motion detectors.

This is as far as I'm able to understand from your post :) the rest of your message I don't follow:

Could you walk me through how I would do a "dump from ser2sock Port 10000"?

Not sure how I could verify tty it's being used by multiple services either?

And I'm completely lost with the last comment ....

Would it be safe to say that the issue is only with the system integrating with SmartThings? The AD2Pi is operating correctly as a "keypad" as-is?

**Comment by f34rdotcom** [comment]
Sorry about that confusion. I was not referring to anything on your osx box just the raspberry pi.

Are you using our latest raspbian I published last week or the older one on your Pi?

If your Pi boots our image it should be possible to telnet to the ip address of the Pi on port 10000 as soon as it boots ~60 seconds after powering on.

Capture some messages over the telnet session and post back.

**Comment by j3tang** [comment]
Alright, I will give that a go.

I setup the system about 3 weeks ago probably, so definitely the image was older.

**Comment by j3tang** [comment]
Ok, so I think this may be it.  I killed and restarted ser2sock and then telnet localhost 10000 and got this:

`!CONFIG>MODE=A&CONFIGBITS=ff05&ADDRESS=18&LRR=N&COM=N&EXP=NNNNN&REL=NNNN&MASK=ffffffff&DEDUPLICATE=N`
`!Reading configuration.`
`!UART init.`
`!VER:ffffffff,V2.2a.8.8,TX;RX;SM;VZ;RF;ZX;RE;AU;3X;CG;DD;MF;L2;KE;M2;CB;DS;ER;CR`
`[10000001000000003A--],008,[f70200071008001c08020000000000],"****DISARMED****  Ready to Arm  "`
`[10000001000000003A--],008,[f70200071008001c08020000000000],"****DISARMED****  Ready to Arm  "`
and then it repeats ...

**Comment by f34rdotcom** [comment]
Ya that looks good and is expected output. I only see one partition in this data you sent so the rest should just work. Do you still see any other issues as described in your original post?

**Comment by j3tang** [comment]
Nothing has changed in terms of the error/warning.
I still receive the text message indicating intrusion and also the siren/audio muted. 

I tried arming from the webapp and I end up with the same notifications through SmartThings. At least that tells me the integration is working ........

Just seems like something isn't setup correctly?

**Comment by f34rdotcom** [comment]
Ya I am sure it is right under our nose but I am not seeing it. Now that I read this again I am wonder why the Ready indicator is in part of SHM at all. 

 The "Ready" indicator is a confusing indicator. It does not indicate any alarms only that the alarm can be armed or is ready to be armed. It can turn on / off for other reasons and is again only an indication of ready to arm and nothing else. 

FYI. I am at my desk "most" days PST if you want to iron this out over a call or possible remote desktop session.

503 443 2000

**Comment by j3tang** [comment]
![screenshot_20181022-154547__01](https://user-images.githubusercontent.com/43900025/47315273-239c4780-d612-11e8-810a-3f53f007a734.jpg)

Screenshot of SmartThings ... there are a few of these types of sensors that I'm not sure if they should or should not be there, but they were all added in automatically when integrating.

Should I just remove the "Ready" contact? And would that have a detrimental effect on the whole system?

I wouldn't be opposed to a phone call, I just don't work from home so I wouldn't be able to test anything over the call.  Maybe one of these days I will take advantage of a work from home day to give you a call.

**Comment by j3tang** [comment]
I'm not sure if I wasn't supposed to do this, but after AD was all setup and all the device type handlers, etc were completely sorted out on the SmartThings developer login, I saw all those contacts in "my things" tab, but I didn't see the integration with SHM. So I treid to set it up myself through the Security portion. There's nothing set in the Fire, Leak, etc.

And yes, in the Security portion it is set to Use Every Open/Close Sensor.

Guess I need some guidance on what some of this stuff means and how it should be set up.

**Comment by f34rdotcom** [comment]
With the next release it will be possible to change the virtual contact device types. So many changes since this ticket so I will close but do re open if it is still applicable.
