### ISSUE TITLE
AlarmDecoder & NuTech Company Offline?

### ISSUE THREAD

**Issue by erikson1970** [nutechsoftware/alarmdecoder#74]
Hey contributors - has anyone heard from the NuTech / AlarmDecoder company lately? Github activity seems to have waned over the last couple years. I was excited to incorporate the USB receiver thingy into my HomeAssistant setup but my recent hardware order through their product portal seems to have gone into a black hole and attempts to contact the company to make inquiries have gone nowhere.  It looks like both web sites are dead and their respective domain registrations are about to expire.  There was an earlier post of their website certificates expiring...so, it seems maybe like an abandoned product. Hope they're all ok.

Sincerely,
Hopeful in Boston

**Comment by star-glider** [comment]
I think they're gone. The alarmdecoder.com domain now redirects to some scammy domain monetization thing. As far as I can tell, Nutech was started by a few guys in 1995 as a tech consultancy form, and AD seems like it was initially just a demo of what they could do (probably one of the founders/employees had an Ademco system), and it became popular enough for them to put some resources behind it. My guess is that the team just retired or lost interest, and they're just letting the domains expire.

It's pretty great that they open-sourced the software, though; I've fixed a bunch of UI bugs on my own and was able to build in Slack notifications with a bit of tweaking. It's too bad that they didn't open source the hardware; the little board itself is fantastic, and based on the silk-screening, they clearly used some kind of on-demand PCB manufacturer that just takes a design file churns out surface-mount PCBs (I forget the specific name). The HA integration is basically perfect.

I only ordered mine about nine months ago when I really got into HA---turns out it was just under the wire. In fairness, though, the supported systems are now all ~20 years old, so probably nearing replacement age anyway.

**Comment by digiblur** [comment]
@star-glider thanks for the detail!  I've been using them myself for quite some time as well.  I'm hoping and praying nothing dies as I use my alarm states for so many things in my smart home automation states.  I did pick up one of their ESP32 boards before they folded but haven't done anything with it honestly as the one on the Pi3 has been working just fine.  

I can see it being tough to keep going given the very small crowd using these now given the age of the hardware.  But damn, everything seems to be cloud based with wireless sensors garbage thrown into houses.  I love my wired sensors!

**Comment by f34rdotcom** [comment]
Sorry people but life has been too busy for me and it is challenging to find enough time for work to survive and pay the bills. I still have some product left but not much. The demand has dropped over the past few years so I don't have as much time to invest. I will work on getting the site back online this year but currently my time is limited to a few IT support contract customers local here in town.

**Comment by jjslegacy** [comment]
Glad to hear everything is okay.  We all get life getting busy.  My system has been humming along thankfully.  

Wonder if we could get some of @star-glider fixes in the GitHub?

**Comment by star-glider** [comment]
Hey @f34rdotcom we all sincerely appreciate the work you all have done to keep our aging systems working like new! I 100% agree with @digiblur about how reliable and well-designed these old systems are. I have one of the Abode systems in a (ironically much older, because its construction predated even the wired systems) vacation home, and it is so much worse. Sensors flit in and out of range, batteries need to be replaced, and the Homekit integration is flaky at best. My 20-year-old Ademco system + AD2PI is batting 1000 on reliability and is instantly responsive. Like @digiblur it's the trigger for the majority of my automatons. It just sits there humming away on an old Pi Zero not complaining and working beautifully with Home Assistant.

I'm more than happy to toss up my little changes on Github or to submit pull requests. OTOH, all I've done is:

1) Fixed the "custom buttons" button on newer versions of iOS Safari so that it displays properly (just using the native button rendering).

2) Fixed the custom notification JSON method (I actually threw up an issue in the AD2Web repository with my patch, since it's a real usability improvement). I have a "security" channel in our family Slack that also pings us when we've left the garage doors open or the gates open, which is why I wanted to get this working. I'll probably move this whole thing over to HA notifications at some point, but my Slack channel thing predated my adoption of HA.

3) Defaulted the "beeps" to off. Since iOS now deletes local storage after a week of no login, the setting no longer sticks, and I often use my phone to disarm the alarm from bed and don't want to accidentally wake up my wife. :) It probably could be changed to set a cookie instead, but dollars to doughnuts Apple will screw that up someday, too. Probably the "right" way to do this would be to expose a setting in the UI, but I was just doing it for myself. If you're using HA exclusively and not the web UI, this makes no difference.

4) Replaced the empty fourth "quick button" on the left (the column that has fire, medical, security) with a "disarm" button. Obviously, this compromises security, since anyone who can get to the /keypad page can disarm the system (and even see the code if they know a little bit about how browsers work), but given that a) it's only available on my most restricted VLAN, and b) the web UI requires a login, I'm comfortable with the convenience tradeoff of one-button disarm. May not be right for everyone, especially if you don't have a segmented guest network.

5) Most bizarrely, I was having a problem with zones randomly having multiples of 100 added to them. E.g., zone 12 would sometimes reflect as zone 112 or 212 or 312. Wreaked havoc with my zone naming. I honestly have no clue why that's happening; it could be something really weird about my system or something related to the ambiguous way that the panels transmit base 10 vs base 16. I stared at the code for a while and couldn't figure it out, so my ugly hack was just to mod 100 the zone, since I have fewer than 100 zones in my setup.

There might be a few others that I'm forgetting; I've enjoyed tinkering around with this home automation stuff as a hobby.

Happy to help out if I can, although I'm very, very far from an expert on these systems and really just tweak things as they annoy me.

@f34rdotcom thanks again for the great product and nicely commented code and for putting it all up here on Github for us hobbyists and tinkerers to play around with!

**Comment by edrikk** [comment]
@star-glider posting your changes as PRs would be amazing, as worst case users can apply them locally.

A few months ago after taking a backup of the usb I tried upgrading the image to Debian Bookworm but unfortunately AD simply wouldn't come up.  Wish we could update the base Debian.

**Comment by erikson1970** [comment]
@f34rdotcom - thanks for following up with the update.  Also totally understand your needing to tend to life rather this audience and thank you for sending the product.  
Kind Regards from Boston.

**Comment by DaVigster** [comment]
@f34rdotcom , ditto the prior thanks and kudos!  As of 2/12/25 you now likely have no product left ;)  I think I purchased your last device -- the AD2pHAT. Still waiting on its arrival. 

My house was built in 2017 and the electrician did a lot of commercial building work. So, I guess he picked what he knew - a Vista 128BPT!  When I saw it I was like "wtf is this?" The Ademco panels might be old, but they do just work. Will be nice to now have the integration with HA.

Thanks again!
-D

**Comment by ajschmidt8** [comment]
Hi everyone. A few years back, @f34rdotcom and I had a video call to discuss AlarmDecoder. After the meeting, he gave me some permissions on this repository and PyPI to help maintain the project.

Using these permissions, I've just merged https://github.com/nutechsoftware/alarmdecoder/pull/75 and published a new PyPI release: https://pypi.org/project/alarmdecoder/1.13.12/. I posted additional details related to this change for Home Assistant here: https://github.com/home-assistant/core/issues/133249#issuecomment-2676931740.

I also merged https://github.com/nutechsoftware/alarmdecoder/pull/76, which introduced a GitHub Actions workflow that will run `pytest` on all pull requests to help ensure future contributions don't break things.

Since my call with @f34rdotcom a few years ago, I've moved and no longer have AlarmDecoder set up at my current property. However, I'm still available to help merge pull requests and deploy new PyPI versions. I don't watch this repository, so the best way to get my attention on PRs that need to be merged is to `@` me.

I appreciate @f34rdotcom's work on AlarmDecoder and hope to keep the project alive with future contributions from the public!

**Comment by veso266** [comment]
Not sure, will the domain ever get back online (I realy hope so) and hopefully maybe some more AD2USB can be meade, so the ones here: https://alarmdecoder.square.site/product/alarmdecoder-usb-ad2usb/1
will not be out of stock

The great thing about this product was that it did not require any cloud subscription, while still being DIY enought so u could constumize it however u wanted

If you can't build anymore of them, maybe u could at least open source the software and the hardware so comunity could work on it, I wish I would buy this in 2021 while I still could (but always said to myself, will do it tomorow, and no there is no tomorow anymore 😢 )

**Comment by sourcebitt** [comment]
@ajschmidt8
@f34rdotcom
Will you be willing to open sourcing the hardware as well? Maybe adding it to this github page, or having a separate one.

**Comment by ajschmidt8** [comment]
> [@ajschmidt8](https://github.com/ajschmidt8) [@f34rdotcom](https://github.com/f34rdotcom) Will you be willing to open sourcing the hardware as well? Maybe adding it to this github page, or having a separate one.

I'll defer to @f34rdotcom for that question. I'm not involved with the hardware.
